### ISSUE TITLE
couchdb cannot be installed

### ISSUE THREAD

**Issue by sscherfke** [spiroid/cozy-couchdb#1]
Running `docker build github.com/spiroid/cozy-couchdb -t dozy/couchdb` results in:
```
Step 4/13 : RUN apt-get -y update && apt-get install --quiet --assume-yes --no-install-recommends     couchdb     && apt-get clean
 ---> Running in c6c710e16d76
Get:1 http://deb.debian.org/debian sid InRelease [231 kB]
Get:2 http://deb.debian.org/debian sid/main amd64 Packages [10.0 MB]
Fetched 10.2 MB in 3s (2931 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 couchdb : Depends: libicu52 (>= 52~m1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get -y update && apt-get install --quiet --assume-yes --no-install-recommends     couchdb     && apt-get clean' returned a non-zero code: 100
```

**Comment by sscherfke** [comment]
I also filed a bug at https://github.com/tianon/docker-brew-debian/issues/61.

Using `ubuntu:latest`might be a workaround until `debian:sid` fixes this issue?

**Comment by sscherfke** [comment]
They suggested to do `echo "deb http://deb.debian.org/debian stable main" > /etc/apt/sources.list.d/debian-stable.list && apt-get update && apt-get install -qy couchdb`. It seems to work.

**Comment by spiroid** [comment]
hi @sscherfke,

Thx for the feedback.
One solution would be to change the base image from _debian:sid_ to _debian_ stable.

Please note however that the use of this image is not required anymore.
I should have done this for months now, but with latest versions of my cozy controller image, you can directly use a standard couchdb docker image.

You can have a look at that docker compose file for more info : https://github.com/spiroid/cozy/blob/refactor-compose-v2/docker-compose.yml

**Comment by sscherfke** [comment]
Looks great, I will try this out.  Are you still actively working on it?

**Comment by spiroid** [comment]
I was working on it a few weeks / months ago.
As i didn't get much traction from the cozy cloud team, i continue to update these images on my free time, which is very limited ... 

First, i'm going to clean all the repositories to make it clear what should be used and what is deprecated.
Then, if you want to help, I can give you the contributor role on the repositories.

I plan to launch a new instance based on that configuration behind a traefix reverse proxy on a personal server.

**Comment by sscherfke** [comment]
I’m not very experienced with cozy yet. I just want to get it running in Docker behind nginx (running on the host). I can provide you with feedback when I make progress or find issues but I don’t think I need contributor permissions (at least, yet). ;-)
